name: Follow Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  follow-sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install requests
    - name: Run sync script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  
        GITHUB_NAME: ${{ secrets.GH_NAME }}  
      run: |
        python script/sync_follow.py
